services:
    monolog.formatter.json.stacktraces:
        class: Monolog\Formatter\JsonFormatter
        calls:
            - [includeStacktraces]
    monolog.formatter.line.stacktraces:
        class: Monolog\Formatter\LineFormatter
        calls:
            - [includeStacktraces]
    monolog.formatter.default:
        alias: monolog.formatter.line.stacktraces
monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]
                formatter:  monolog.formatter.default
            # uncomment to get logging in your browser
            # you may have to allow bigger header sizes in your Web server configuration
            #firephp:
            #    type: firephp
            #    level: info
            #chromephp:
            #    type: chromephp
            #    level: info
            stdout:
                type: stream
                path: php://stdout
                level: debug
                channels: ['!event']
                formatter:  monolog.formatter.default
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 100 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: "php://stderr"
                level: debug
                formatter: monolog.formatter.default
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
