include:
  - local: 'gitlab-ci/templates/k8s.gitlab-ci.yml'

deploy k8s start:
  stage: 'deploy'
  extends:
    - '.deploy k8s start'
  environment:
    deployment_tier: development
    on_stop: deploy k8s stop
    auto_stop_in: 6 week
  needs:
    - 'build back stable'
    - 'build front stable'
  rules:
    - if: '$FEATURE_DEPLOY_MR_ON_K8S != "1"'
      when: never
    - !reference [.MR rules, rules]
  when: manual

deploy k8s stop:
  stage: 'deploy'
  extends:
    - '.deploy k8s stop'
  needs:
    - 'deploy k8s start'
  rules:
    - if: '$FEATURE_DEPLOY_MR_ON_K8S != "1"'
      when: never
    - !reference [.MR rules, rules]
  when: manual

remove stable images:
  stage: 'cleanup'
  extends:
    - '.delete image'
  needs:
    - 'deploy k8s stop'
  script:
    - ./reg rm -d --auth-url $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $BACK_IMAGE_STABLE
    - ./reg rm -d --auth-url $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $FRONT_IMAGE_STABLE
  rules:
    - if: '$FEATURE_DEPLOY_MR_ON_K8S != "1"'
      when: never
    - !reference [.MR rules, rules]
  when: on_success

